version: "3"
services:
  client:
    build: ./app/client
    hostname: 'todo_client'
    container_name: 'todo_client'
    stdin_open: true
    ports:
      - 3000:3000
  api:
    build: ./app/api
    hostname: 'todo_api'
    container_name: 'todo_api'
    ports:
      - 8080:8080
  postgres:
    image: postgres:14.0
    hostname: 'postgres'
    container_name: 'postgres'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=mangodb
  mangodb:
    image: ghcr.io/mangodb-io/mangodb:latest
    hostname: 'mangodb'
    container_name: 'mangodb'
    command:
      [
        '-listen-addr=:27017',
        '-postgresql-url=postgres://postgres@postgres:5432/mangodb',
      ]
    ports:
      - 27017:27017
