---
services:
  todo_client:
    build: ./app/client
    stdin_open: true

  todo_api:
    build: ./app/api

  nginx:
    image: nginx
    ports:
      - 8888:8888
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: ghcr.io/ferretdb/postgres-documentdb:latest
    platform: linux/amd64
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:2
    ports:
      - 27017:27017
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://username:password@postgres:5432/postgres
